DEFINITION_FIELDS = {
    "name",
    "asset_type",
    "category_id",
    "unit_name",
    "description",
    "manufacturer",
    "model",
    "replacement_value",
    "rental_recoup_days",
    "rental_maintenance_cost_per_day",
    "rental_profit_margin_percent",
    "notes",
}
TRACKED_UNIT_FIELDS = {
    "status",
    "condition",
    "current_location_id",
    "current_holder_user_id",
    "manufacturer",
    "model",
    "serial_number",
    "asset_tag",
    "replacement_value",
    "notes",
}
